# ExCAPE genes are the keys, and DUD-E genes are the values
declare -A excape2dude
excape2dude['ADORA2A']='aa2ar'
excape2dude['ABL1']='abl1'
excape2dude['ACE']='ace'
excape2dude['ACHE']='aces'
excape2dude['ADA']='ada'
excape2dude['ADAM17']='ada17'
excape2dude['ADRB1']='adrb1'
excape2dude['ADRB2']='adrb2'
excape2dude['AKT1']='akt1'
excape2dude['AKT2']='akt2'
excape2dude['AKR1B1']='aldr'
excape2dude['AR']='andr'
excape2dude['MAOB']='aofb'
excape2dude['BACE1']='bace1'
excape2dude['BRAF']='braf'
excape2dude['CA2']='cah2'
excape2dude['CASP3']='casp3'
excape2dude['CDK2']='cdk2'
excape2dude['COMT']='comt'
excape2dude['CYP2C9']='cp2c9'
excape2dude['CYP3A4']='cp3a4'
excape2dude['CSF1R']='csf1r'
excape2dude['CXCR4']='cxcr4'
excape2dude['PDF']='def'
excape2dude['HSD11B1']='dhi1'
excape2dude['DPP4']='dpp4'
excape2dude['DRD3']='drd3'
excape2dude['DHFR']='dyr'
excape2dude['EGFR']='egfr'
excape2dude['ESR1']='esr1'
excape2dude['ESR2']='esr2'
excape2dude['F10']='fa10'
excape2dude['F7']='fa7'
excape2dude['FABP4']='fabp4'
excape2dude['PTK2']='fak1'
excape2dude['FGFR1']='fgfr1'
excape2dude['FKBP1A']='fkb1a'
excape2dude['FDPS']='fpps'
excape2dude['NR3C1']='gcr'
excape2dude['GBA']='glcm'
excape2dude['GRIA2']='gria2'
excape2dude['GRIK1']='grik1'
excape2dude['HDAC2']='hdac2'
excape2dude['HDAC8']='hdac8'
excape2dude['HMGCR']='hmdh'
excape2dude['HSP90AA1']='hs90a'
excape2dude['GCK']='hxk4'
excape2dude['IGF1R']='igf1r'
excape2dude['ITGAL']='ital'
excape2dude['JAK2']='jak2'
excape2dude['KIF11']='kif11'
excape2dude['KIT']='kit'
excape2dude['PRKCB']='kpcb'
excape2dude['LCK']='lck'
excape2dude['LTA4H']='lkha4'
excape2dude['MAPKAPK2']='mapk2'
excape2dude['NR3C2']='mcr'
excape2dude['MET']='met'
excape2dude['MAPK1']='mk01'
excape2dude['MAPK10']='mk10'
excape2dude['MAPK14']='mk14'
excape2dude['MMP13']='mmp13'
excape2dude['MAP2K1']='mp2k1'
excape2dude['NOS1']='nos1'
excape2dude['PLA2G2A']='pa2ga'
excape2dude['PARP1']='parp1'
excape2dude['PDE5A']='pde5a'
excape2dude['PTGS1']='pgh1'
excape2dude['PTGS2']='pgh2'
excape2dude['PLK1']='plk1'
excape2dude['PNP']='pnph'
excape2dude['PPARA']='ppara'
excape2dude['PPARD']='ppard'
excape2dude['PPARG']='pparg'
excape2dude['PGR']='prgr'
excape2dude['PTPN1']='ptn1'
excape2dude['PYGM']='pygm'
excape2dude['DHODH']='pyrd'
excape2dude['REN']='reni'
excape2dude['ROCK1']='rock1'
excape2dude['RXRA']='rxra'
excape2dude['AHCY']='sahh'
excape2dude['SRC']='src'
excape2dude['TGFBR1']='tgfr1'
excape2dude['THRB']='thb'
excape2dude['F2']='thrb'
excape2dude['PRSS1']='try1'
excape2dude['TYMS']='tysy'
excape2dude['PLAU']='urok'
excape2dude['KDR']='vgfr2'
excape2dude['WEE1']='wee1'
excape2dude['XIAP']='xiap'


# Download pdbs into 'receptors' directory
cd ~/repos/dockgym/receptors/

# Use ExCAPE name. Maybe in the supplementary info you could put a table with the correspondence
# between ExCAPE name and DUD-E name
for excape_gene in "${!excape2dude[@]}"; do
    pymol "$excape_gene"_receptor.pdb
    pymol "$excape_gene"_receptor.pdb
    adt "$excape_gene"_receptor.pdb
    adt "$excape_gene"_receptor.pdb
done
