name: Linting and code formatting

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install flake8 yapf mypy pytest types-pkg_resources
    - name: Check for yapf formatting
      run: |
        # stop build if yapf formatting fails
        yapf --diff --recursive .
    - name: Lint with flake8
      run: |
        # stop build if flake8 formatting fails
        flake8 .
    - name: Check type annotations with mypy
      run: |
        # stop build if mypy fails
        mypy .
