name: Linting and code formatting

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install pre-commit
      run: |
        pip install pre-commit
    - name: Run all pre-commit checks
      run: |
        pre-commit run --verbose --all-files
